#!/usr/bin/env node
/**
 * scripts/sync-icons.mjs
 * ----------------------
 * Write each page's icon sprite from `scripts/icons.mjs`, or check that it is
 * current.
 *
 *   node scripts/sync-icons.mjs           # rewrite the sprite in every page
 *   node scripts/sync-icons.mjs --check   # fail if any page is stale
 *
 * ── WHY A GENERATOR AND NOT SIX COPIES ─────────────────────────────────────
 * These are static files with no build step, so a sprite has to be physically
 * present in each page. Six hand-maintained copies of the same block is the
 * shape this project has been bitten by repeatedly — two documents, two routes,
 * two READMEs — and the answer every time was one source and a check.
 *
 * A page gets **only the marks it uses**, so the homepage is not carrying the
 * licensing matrix's icons. The block is rewritten between markers; everything
 * outside them is untouched.
 *
 * ── WHAT --check CATCHES ───────────────────────────────────────────────────
 *   1. A page whose sprite does not match what its `<use>` calls need.
 *   2. A `<use href="#i-...">` naming a mark that does not exist.
 *   3. A page that still has the marker but lost its sprite.
 *
 * (2) is the one that matters. The icon font it replaces failed silently: a
 * misspelled class rendered nothing and reported nothing, which is how a header
 * could ship with an invisible button.
 *
 * Exit 0 clean · 1 stale or undefined mark.
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { ICONS, STROKE } from './icons.mjs';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

const PAGES = [
    'index.html',
    'compliance.html',
    'licensing.html',
    'gallery.html',
    'book.html',
];

const OPEN = '<!-- ICON SPRITE: generated by scripts/sync-icons.mjs. Do not edit by hand. -->';
const CLOSE = '<!-- /ICON SPRITE -->';

const STROKE_ATTRS = Object.entries(STROKE)
    .map(([k, v]) => `${k}="${v}"`)
    .join(' ');

/** Every `#i-name` a page actually calls. */
function usedBy(html) {
    const ids = new Set();
    for (const m of html.matchAll(/<use\s+href="#i-([a-z0-9-]+)"/g)) ids.add(m[1]);
    return [...ids].sort();
}

function sprite(ids) {
    if (ids.length === 0) return `${OPEN}\n  ${CLOSE}`;
    const symbols = ids
        .map((id) => {
            const icon = ICONS[id];
            const attrs = icon.filled
                ? 'fill="currentColor" stroke="none"'
                : `fill="none" stroke="currentColor" ${STROKE_ATTRS}`;
            return `    <symbol id="i-${id}" viewBox="0 0 24 24" ${attrs}>${icon.body}</symbol>`;
        })
        .join('\n');
    return [
        OPEN,
        '  <svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" aria-hidden="true" focusable="false" style="position:absolute">',
        symbols,
        '  </svg>',
        `  ${CLOSE}`,
    ].join('\n');
}

const check = process.argv.includes('--check');
let stale = 0;
let undef = 0;
let total = 0;

for (const page of PAGES) {
    const file = path.join(ROOT, page);
    let html;
    try {
        html = await fs.readFile(file, 'utf8');
    } catch {
        continue;
    }

    const ids = usedBy(html);
    const missing = ids.filter((id) => !ICONS[id]);
    if (missing.length) {
        console.error(`  UNDEFINED  ${page} → ${missing.map((m) => `#i-${m}`).join(', ')}`);
        undef += missing.length;
        continue;
    }
    total += ids.length;

    const start = html.indexOf(OPEN);
    if (start === -1) {
        if (ids.length === 0) continue;
        console.error(`  NO MARKER  ${page} uses ${ids.length} mark(s) and has no sprite block`);
        stale += 1;
        continue;
    }
    const end = html.indexOf(CLOSE, start);
    if (end === -1) {
        console.error(`  UNCLOSED   ${page} sprite block has no closing marker`);
        stale += 1;
        continue;
    }

    const current = html.slice(start, end + CLOSE.length);
    const wanted = sprite(ids);
    // Compare on normalised newlines and write in the file's own convention.
    // These pages live in a repository checked out on Windows: a page rewritten
    // by any tool that emits CRLF would otherwise read as permanently stale,
    // and a check that is always red is a check somebody switches off.
    const crlf = html.includes('\r\n');
    if (current.replace(/\r\n/g, '\n') === wanted) continue;

    if (check) {
        console.error(`  STALE      ${page} (${ids.length} mark(s) in use)`);
        stale += 1;
    } else {
        const block = crlf ? wanted.replace(/\n/g, '\r\n') : wanted;
        await fs.writeFile(file, html.slice(0, start) + block + html.slice(end + CLOSE.length));
        console.log(`  written    ${page} — ${ids.length} mark(s)`);
    }
}

if (undef || stale) {
    console.error(
        `\n  ${undef ? `${undef} undefined mark(s). ` : ''}${
            stale ? `${stale} page(s) stale — run \`npm run icons:sync\`.` : ''
        }\n`,
    );
    process.exit(1);
}

console.log(
    `\n  ${check ? 'Every page carries the sprite its marks need' : 'Sprites written'} · ${total} reference(s) across ${PAGES.length} page(s)\n`,
);
